universe = vanilla
executable = /afs/cern.ch/work/c/cvilela/private/snd_muon_reco/scripts/lxplus_generate_nu.sh
arguments = /eos/user/c/cvilela/SND_ANALYSIS_Feb18/neutrino/nueDefault/ 2000 $(Item) 12 Default
log=/afs/cern.ch/work/c/cvilela/private/genie_nue_$(Item).log
output=/afs/cern.ch/work/c/cvilela/private/genie_nue_$(Item).out
error=/afs/cern.ch/work/c/cvilela/private/genie_nue_$(Item).err
should_transfer_files = NO
request_CPUs = 1
+JobFlavour = "tomorrow"
notify_user = c.vilela@cern.ch
notification = Error
queue from seq 0 99 | 